### ISSUE TITLE
Changelog generation stopped working

### ISSUE THREAD

**Issue by nforro** [packit/prepare-release#9]
It seems that ~2 weeks ago GitHub has stopped putting PR description into merge commits (there is only title), so there are no release notes and the `changelog.py` script doesn't produce anything.
See for example https://github.com/packit/specfile/commit/aea1515b4862fa6fcfe936c64203756f0f04aabb (as opposed to an older https://github.com/packit/specfile/commit/3569ab649fce10bbae93e54400e204e4981ace92).

**Comment by nforro** [comment]
It seems it's configurable and we should switch from `Default message` to `Default to pull request title and description` in all our projects.

![gh](https://user-images.githubusercontent.com/14923067/215486249-2aa76ece-6def-42ff-9dca-41039a46391f.png)

**Comment by nforro** [comment]
I've switched the config option in all projects, so it should be resolved.
Just a heads-up for @lbarcziova and @FrNecas, you'll probably have to extract release notes from PRs merged last week (or two) manually.

**Comment by mfocko** [comment]
@nforro I wonder if it helps even with the projects where the merge is done by Zuul, cause I'd expect it to be independent

**Comment by nforro** [comment]
I think the [softwarefactory-project-zuul](https://github.com/apps/softwarefactory-project-zuul) bot just tells GitHub to merge a PR and it works the same way as if you would press the **Merge pull request** button.
